// Enterprise-grade Security Helpers for the GenAI PromptWars Evaluator

// Blocklist of prompt injection phrases (case-insensitive)
const PROMPT_INJECTION_KEYWORDS = [
  "ignore previous instructions",
  "ignore all directives",
  "system prompt",
  "you are now a",
  "override system",
  "bypass safety",
  "instead of your instructions",
];

/**
 * Scans an input string for known prompt injection payloads
 */
export function hasPromptInjection(input: string): boolean {
  if (!input) return false;
  const normalized = input.toLowerCase();
  return PROMPT_INJECTION_KEYWORDS.some((keyword) => normalized.includes(keyword));
}

/**
 * Sanitizes output generated by GenAI models to prevent XSS script injection attacks
 */
export function sanitizeOutput(text: string): string {
  if (!text) return "";
  
  return text
    .replace(/<script[^>]*>([\s\S]*?)<\/script>/gi, "") // Remove script tags
    .replace(/on\w+="[^"]*"/gi, "") // Remove inline event handlers (e.g. onload, onclick)
    .replace(/on\w+='[^']*'/gi, "")
    .replace(/javascript:[^\s"']*/gi, "") // Remove javascript: protocol links
    .trim();
}
